# Generated by Django 6.0.7 on 2026-07-17 05:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisCatering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Jenis Catering',
            },
        ),
        migrations.CreateModel(
            name='KategoriMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori Menu',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('petugas', 'petugas'), ('pelanggan', 'Pelanggan')], default='pelanggan', max_length=20)),
                ('is_approved', models.BooleanField(default=False, help_text='Khusus role pelanggan. True jika registrasi sudah disetujui petugas.')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('no_telepon', models.CharField(blank=True, max_length=20)),
                ('alamat', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'petugas'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_paket', models.CharField(max_length=150)),
                ('deskripsi', models.TextField(blank=True)),
                ('harga_per_porsi', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('status_stok', models.CharField(choices=[('tersedia', 'Tersedia'), ('kosong', 'Kosong')], default='tersedia', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, limit_choices_to={'role': 'administrator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_dibuat', to=settings.AUTH_USER_MODEL)),
                ('jenis_catering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_list', to='administrator.jeniscatering')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_list', to='administrator.kategorimenu')),
            ],
            options={
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pesanan', models.CharField(editable=False, max_length=30, unique=True)),
                ('nama_pemesan', models.CharField(max_length=150)),
                ('alamat', models.TextField()),
                ('no_telepon', models.CharField(max_length=20)),
                ('waktu_acara', models.DateTimeField()),
                ('jumlah_porsi', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('catatan_tambahan', models.TextField(blank=True)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('menunggu_pembayaran', 'Menunggu Pembayaran'), ('diproses', 'Diproses'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='menunggu_pembayaran', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diproses_oleh', models.ForeignKey(blank=True, limit_choices_to={'role': 'petugas'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesanan_diproses', to=settings.AUTH_USER_MODEL)),
                ('jenis_catering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesanan_list', to='administrator.jeniscatering')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesanan_list', to='administrator.menu')),
                ('pelanggan', models.ForeignKey(limit_choices_to={'role': 'pelanggan'}, on_delete=django.db.models.deletion.CASCADE, related_name='pesanan_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pesanan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode', models.CharField(choices=[('transfer_bank', 'Transfer Bank'), ('e_wallet', 'E-Wallet'), ('qris', 'QRIS'), ('tunai', 'Tunai')], max_length=20)),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bukti_bayar', models.ImageField(upload_to='bukti_pembayaran/')),
                ('status_verifikasi', models.CharField(choices=[('menunggu', 'Menunggu Verifikasi'), ('valid', 'Valid'), ('tidak_valid', 'Tidak Valid')], default='menunggu', max_length=20)),
                ('catatan_verifikasi', models.TextField(blank=True)),
                ('tanggal_verifikasi', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diverifikasi_oleh', models.ForeignKey(blank=True, limit_choices_to={'role': 'petugas'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_diverifikasi', to=settings.AUTH_USER_MODEL)),
                ('pesanan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='administrator.pesanan')),
            ],
            options={
                'verbose_name_plural': 'Pembayaran',
            },
        ),
    ]
