# Generated by Django 6.0.6 on 2026-07-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Khusus role pelanggan. True jika registrasi sudah disetujui operator.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('operator', 'Operator'), ('pelanggan', 'Pelanggan')], default='pelanggan', max_length=20),
        ),
    ]
