# Generated by Django 6.0.6 on 2026-07-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_user_is_approved_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Khusus role pelanggan. True jika registrasi sudah disetujui petugas.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('petugas', 'petugas'), ('pelanggan', 'Pelanggan')], default='pelanggan', max_length=20),
        ),
    ]
