# Generated by Django 6.0.6 on 2026-07-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_user_is_approved_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimal_hari_pemesanan', models.PositiveIntegerField(default=3)),
                ('maksimal_porsi_harian', models.PositiveIntegerField(default=1000)),
            ],
        ),
    ]
