# Generated by Django 6.0.6 on 2026-07-19 15:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_user_is_approved_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_porsi', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_pesanan_list', to='administrator.menu')),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_list', to='administrator.pesanan')),
            ],
            options={
                'verbose_name_plural': 'Item Pesanan',
            },
        ),
    ]
