# Generated by Django 6.0.6 on 2026-07-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_itempesanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='bukti_bayar',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/'),
        ),
    ]
