# Generated by Django 6.0.7 on 2026-07-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_pembayaran_bukti_bayar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='jenis_catering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_list', to='administrator.jeniscatering'),
        ),
    ]
