# Generated by Django 6.0.6 on 2026-07-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_pembayaran_bukti_bayar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persentase_dp', models.PositiveIntegerField(default=50, verbose_name='Persentase DP (%)')),
            ],
            options={
                'verbose_name': 'Pengaturan Pembayaran',
                'verbose_name_plural': 'Pengaturan Pembayaran',
            },
        ),
    ]
