# Generated by Django 6.0.6 on 2026-07-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_pengaturan'),
        ('administrator', '0006_alter_menu_jenis_catering'),
    ]

    operations = [
    ]
