# Generated by Django 6.0.6 on 2026-07-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_pengaturanpembayaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanJeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimal_hari', models.PositiveIntegerField(default=3)),
                ('deskripsi', models.TextField(blank=True)),
            ],
        ),
    ]
