# Generated by Django 6.0.6 on 2026-07-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_merge_0004_pengaturan_0006_alter_menu_jenis_catering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaturan',
            name='maksimal_porsi_harian',
        ),
        migrations.RemoveField(
            model_name='pengaturan',
            name='minimal_hari_pemesanan',
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='alamat',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='deskripsi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='nama_catering',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='nama_website',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
