# Generated by Django 6.0.6 on 2026-07-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_remove_pengaturan_maksimal_porsi_harian_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaturan',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='pengaturan',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='pengaturan',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pengaturan',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='pengaturan',
            name='nama_catering',
        ),
        migrations.RemoveField(
            model_name='pengaturan',
            name='nama_website',
        ),
        migrations.RemoveField(
            model_name='pengaturan',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='atas_nama',
            field=models.CharField(default='Meja Nusantara', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='maksimal_porsi_harian',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='minimal_hari_pemesanan',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='nama_bank',
            field=models.CharField(default='BCA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='nomor_rekening',
            field=models.CharField(default=1234567890, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='qris',
            field=models.ImageField(blank=True, null=True, upload_to='qris/'),
        ),
    ]
