# Generated by Django 6.0.6 on 2026-07-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_remove_pengaturan_alamat_remove_pengaturan_deskripsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturan',
            name='alamat',
            field=models.TextField(default='Alamat belum diisi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='email',
            field=models.EmailField(default=3, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='nama_catering',
            field=models.CharField(default=1000, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='whatsapp',
            field=models.CharField(default='BCA', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pengaturan',
            name='atas_nama',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pengaturan',
            name='nama_bank',
            field=models.CharField(default='BCA', max_length=100),
        ),
        migrations.AlterField(
            model_name='pengaturan',
            name='nomor_rekening',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
