# Generated by Django 6.0.6 on 2026-07-27 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_pengaturan_alamat_pengaturan_email_pengaturan_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanPemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_otomatis', models.BooleanField(default=False, help_text='Jika aktif, minimal H- pemesanan otomatis menyesuaikan jumlah pesanan aktif.')),
                ('minimal_hari_manual', models.PositiveIntegerField(default=3, help_text='Minimal H- pemesanan yang dipakai saat mode otomatis dimatikan. Contoh: 3 = pesanan minimal 3 hari sebelum acara.', validators=[django.core.validators.MinValueValidator(0)])),
                ('batas_pesanan_sedang', models.PositiveIntegerField(default=10, help_text="Jika jumlah pesanan aktif mencapai angka ini, minimal H- dinaikkan ke 'H- saat sedang ramai'.")),
                ('hari_saat_sedang', models.PositiveIntegerField(default=5, help_text='Minimal H- pemesanan saat jumlah pesanan aktif tergolong sedang ramai.', validators=[django.core.validators.MinValueValidator(0)])),
                ('batas_pesanan_padat', models.PositiveIntegerField(default=20, help_text="Jika jumlah pesanan aktif mencapai angka ini, minimal H- dinaikkan ke 'H- saat padat'.")),
                ('hari_saat_padat', models.PositiveIntegerField(default=7, help_text='Minimal H- pemesanan saat jumlah pesanan aktif tergolong padat/kewalahan.', validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Pemesanan',
                'verbose_name_plural': 'Pengaturan Pemesanan',
            },
        ),
        migrations.DeleteModel(
            name='Pengaturan',
        ),
    ]
