# Generated by Django 6.0.6 on 2026-07-28 03:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_pengaturanpemesanan_delete_pengaturan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wajib_dp', models.BooleanField(default=False, help_text='Jika aktif, pelanggan wajib membayar DP sebelum pesanan diproses petugas.')),
                ('persen_dp', models.PositiveIntegerField(default=50, help_text='Persentase DP dari total harga pesanan. Contoh: 50 = DP minimal 50% dari total.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan DP',
                'verbose_name_plural': 'Pengaturan DP',
            },
        ),
        migrations.AlterModelOptions(
            name='pembayaran',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Pembayaran'},
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='jenis',
            field=models.CharField(choices=[('dp', 'DP (Uang Muka)'), ('pelunasan', 'Pelunasan'), ('penuh', 'Bayar Penuh')], default='penuh', max_length=20),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='persen_dp',
            field=models.PositiveIntegerField(blank=True, help_text='Snapshot persentase DP yang berlaku untuk pesanan ini (jika wajib_dp=True).', null=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='status_pembayaran',
            field=models.CharField(choices=[('belum_bayar', 'Belum Bayar'), ('dp_menunggu_verifikasi', 'DP Menunggu Verifikasi'), ('dp_terverifikasi', 'DP Terverifikasi (Menunggu Pelunasan)'), ('pelunasan_menunggu_verifikasi', 'Menunggu Verifikasi'), ('lunas', 'Lunas')], default='belum_bayar', max_length=40),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='wajib_dp',
            field=models.BooleanField(default=False, help_text='Snapshot: apakah pesanan ini wajib DP (diambil dari pengaturan saat pesanan dibuat).'),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='pesanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran_list', to='administrator.pesanan'),
        ),
    ]
